### ISSUE TITLE
Error On Ha Esphome 

### ISSUE THREAD

**Issue by thecivvie** [tfyoung/esphome-junctek_kgf#5] opened 2022-12-31 18:07 UTC
I am getting this error when compiling on home assistant

`
src/esphome/components/junctek_kgf/junctek_kgf.cpp: In function 'int getval(const char*&)':
src/esphome/components/junctek_kgf/junctek_kgf.cpp:19:46: error: exception handling disabled, use -fexceptions to enable
     throw std::runtime_error("invalid number");
                                              ^
In file included from src/esphome/components/sensor/sensor.h:3,
                 from src/esphome/components/junctek_kgf/junctek_kgf.h:4,
                 from src/esphome/components/junctek_kgf/junctek_kgf.cpp:1:
src/esphome/components/junctek_kgf/junctek_kgf.cpp: In member function 'void JuncTekKGF::handle_line()':
src/esphome/components/junctek_kgf/junctek_kgf.cpp:125:42: error: 'e' was not declared in this scope
     ESP_LOGE("JunkTekKGF", "Error %s %s",e.what(), buffer);
                                          ^
src/esphome/core/log.h:123:89: note: in definition of macro 'esph_log_e'
   esp_log_printf_(ESPHOME_LOG_LEVEL_ERROR, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                         ^~~~~~~~~~~
src/esphome/components/junctek_kgf/junctek_kgf.cpp:125:5: note: in expansion of macro 'ESP_LOGE'
     ESP_LOGE("JunkTekKGF", "Error %s %s",e.what(), buffer);
     ^~~~~~~~
*** [/data/juncteks/.pioenvs/juncteks/src/esphome/components/junctek_kgf/junctek_kgf.cpp.o] Error 1
========================= [FAILED] Took 11.33 seconds =========================
`

Any suggestions as to what to change.

**Comment by tfyoung** [comment] 2023-01-06 11:16
Duplicate of #4

**Closed** 2023-01-06 11:17 UTC
